name: Build Test and Deploy
on:
  push:
    branches:
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install packages
      run: yarn install

    - name: Build and test
      run: yarn test


  deploy-and-push-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo ${{ secrets.DOCKERHUB_USERNAME }}/to-do-app:${{ steps.vars.outputs.sha_short }}
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"


    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/to-do-app:${{ steps.vars.outputs.sha_short }}

  


  # apply-infrastructure:
  #   needs: [build-and-test, deploy-and-push-docker-image]
  #   runs-on: ubuntu-latest

  #   steps: 
  #   - name: terraform apply
  #     run: echo "Will apply terraform files."
